### ISSUE TITLE
Binder prevents graceful shutdown. 

### ISSUE THREAD

**Issue by kelseyh** [spring-cloud/spring-cloud-stream-binder-jms#27]
It looks like the culprit is the DefaultMessageListenerContainer created by the ListenerContainerFactory prevents graceful shutdown of the container. One solution seems to be to set the DefaultMessageListener#taskExecutor to a ThreadPoolTaskExecutor bean. 
I have tried a number of ways to achieve that to no avail. 

1.  Override the beans created in JmsBinderGlobalConfiguration, this doesn't work because the beans in JmsBinderGlobalConfiguration are always the last to be created. 
2. Create a BeanPostProcessor to change the JmsMessageDrivenChannelAdapter#listenerContainerFactory to my own implementation which adds a taskExecutor but these beans are never post processed by my processor. 
3. Aspect(Spring AOP) ListenerContainerFactory#build to set DefaultMessageListenerContainer#taskExecutor.

I believe none of the above work because Stream creates a new ApplicationContext which is unaffected by any of the above. 
The only solution seems to be to patch binder source code until a solution can be found.  
Please see attached patch and a simple sample app that demonstrates the problem using 1.0.0.BUILD-SNAPSHOT of the binder.

To reproduce the problem just run the app and then request it's shutdown via jmx.
[demo.zip](https://github.com/spring-cloud/spring-cloud-stream-binder-jms/files/986012/demo.zip)

[Updated_ListenerContainerFactory_to_accept_a_TaskExecutor_Added_ThreadPoolTaskExecutor_bea.patch.zip](https://github.com/spring-cloud/spring-cloud-stream-binder-jms/files/986025/Updated_ListenerContainerFactory_to_accept_a_TaskExecutor_Added_ThreadPoolTaskExecutor_bea.patch.zip)

If there is a simpler solution please let me know.

**Comment by artembilan** [comment]
I think the main issue here that `AbstractMessageChannelBinder` doesn't register `MessageProducer` as a bean, therefore its `destroy()` isn't called. We have only this code there:
```
public final void unbind() {
	if (this.lifecycle != null) {
		this.lifecycle.stop();
	}
	afterUnbind();
}
```
and nowhere we call `destroy()` which delegates to the `JmsMessageDrivenEndpoint`:
```
if (this.isRunning()) {
	this.stop();
}
this.listenerContainer.destroy();
```

//CC @mbogoevici , @garyrussell

**Comment by mbogoevici** [comment]
At some point in the future we might make all of them beans, but right now we can call `destroy` on the `lifecycle` if it is also a `DisposableBean`.

**Comment by mbogoevici** [comment]
(Case in which this needs to be reported in core).

**Comment by artembilan** [comment]
> Case in which this needs to be reported in core

Well, it is reported where the problem appears. 
That is already our internal kitchen how to move or fix the issue.
Fully unrelated to the end-user experience...

**Comment by artembilan** [comment]
Thanks for confirmation though, @mbogoevici !

**Comment by mbogoevici** [comment]
I've opened https://github.com/spring-cloud/spring-cloud-stream/issues/953  in core for handling this. Thanks for reporting @kelseyh and thanks for looking into this @artembilan.
