### ISSUE TITLE
Header names should be JMS spec compliant

### ISSUE THREAD

**Issue by donovanmuller** [spring-cloud/spring-cloud-stream-binder-jms#8]
As per the JMS spec, header names must be *valid Java identifier part characters*.
This means that any header names that contain illegal characters (`-` for example) should be handled correctly?

See http://download.oracle.com/otn-pub/jcp/jms-2_0-fr-eval-spec/JMS20.pdf

**Comment by mbogoevici** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-stream-binder-jms/commit/5abd5907a400673dc913d19c43b9ccb6f860f442
